### ISSUE TITLE
BUG case in Encoder: floating number but categorical

### ISSUE THREAD

**Issue by luofanghao** [usc-isi-i2/dsbox-cleaning#7]
As in our designed API, if a column only contains two types of cell: blank cells (missing value) and one other value.  Encoder should recognize this column as categorical column and convert it to a column with binary values.

for example, "ca" column in [231 dataset](https://github.com/luofanghao/missingValue_data/blob/master/231/data.csv) should be converted to ..0,0,0...,1,0,..
but our current version of Encoder outputs the original column because of some reason.

I think we should keep out designed API but @rpedsel said it is hard to do and should let @kyao to decide. So could @rpedsel please describe the problem in this issue?

**Comment by rpedsel** [comment]
I won't say it is bug...In the original design of the encoder, it first identifies data type of the column, for floating numbers, they are consider real and would never fall into categories. For the 231 dataset, "ca" column is declared as "real"/"numeric", so the python package (liac-arff) used to convert ARFF to CSV just made the column floating numbers(ex. 0.0, 1.0). That's why the encoder doesn't do anything on the column. 

So now the decision to make is whether we should include floating number columns with 1 unique value (or 2, or all that pass categorical determining rules?) as categorical. Or this should be done for those single/binary float columns that are actually of all integer values (1.0, 2.0...). 

On the other hand, I guess what actually causes problem here, is that people who create those ARFF did't declare column(attribute in ARFF file) data type precisely. In those ARFF files, it's common to see only REAL or NUMERIC for the whole data set, even when all values in some column are integers. If we want to cater this issue, we need to re-determine column data type ourselves. (so that we have converted CSV files of probably better format). However, this may also change properties of the original ARFF data set (maybe those attributes declared as REAL/NUMERIC for some plausible reasons.)

**Comment by kyao** [comment]
This is one of the strange corner cases. If the creator of the data set did declare the column to be real, then we probably should respect that even if there is only one unique value. For now let's treat the column as real, and the rest of our preprocessing code should preform correctly even if it there is only one unique value. We can revisit this issue if this problem comes up again.

**Comment by luofanghao** [comment]
Hi @kyao , I solve this corner case in the Imputer in this commit:
https://github.com/usc-isi-i2/dsbox-cleaning/commit/6b0498498d37ad8b16a71b13a5aeb718954a9720

It works now. Do you think this way is a good idea?
